{% set name = "aom" %}
{% set version = "3.6.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://storage.googleapis.com/aom-releases/libaom-{{ version }}.tar.gz
  sha256: 42b862f58b3d00bd3902d2dc469526574f5b012e5b178e6a9652845a113d6887
  patches:
    - do_not_link_to_libm_windows.patch

build:
  number: 0
  run_exports:
    # Just a guess...
    - {{ pin_subpackage('aom', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - perl
    - nasm
    - make   # [unix]

test:
  commands:
    - aomenc --help  # [build_platform == target_platform]
    - aomdec --help  # [build_platform == target_platform]
    - test -f ${PREFIX}/include/aom/aom.h            # [unix]
    - test -f ${PREFIX}/lib/libaom${SHLIB_EXT}       # [unix]
    - test ! -f ${PREFIX}/lib/libaom.a               # [unix]
    - test -f ${PREFIX}/lib/pkgconfig/aom.pc         # [unix]
    - if not exist %LIBRARY_INC%\\aom\\aom.h exit 1  # [win]
    - if not exist %LIBRARY_BIN%\\aom.dll exit 1     # [win]

about:
  home: https://aomedia.org/
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Alliance for Open Media video codec
  description: |
    AOMedia Video 1 (AV1), is an open, royalty-free video coding format designed for
    video transmissions over the Internet.
  dev_url: https://aomedia.googlesource.com/aom/
extra:
  recipe-maintainers:
    - matthiasdiener
